name = "Tectonic Cliftree"
author = "Nyx"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c8b5487e7047f2e022bca71a224b1fd0969e35b28193b8185af052ccf769332"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.6", "1.21.7"]
